In [1]:
import numpy as np

In [2]:
print("--- Завдання 1: Одновимірний масив з першими 10 натуральними числами ---")
vector_natural = np.arange(1, 11)
print(f"Вектор з першими 10 натуральними числами:\n{vector_natural}\n")

--- Завдання 1: Одновимірний масив з першими 10 натуральними числами ---
Вектор з першими 10 натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]



In [3]:
print("--- Завдання 2: Двовимірний масив 3x3, заповнений нулями ---")
matrix_zeros = np.zeros((3, 3))
print(f"Матриця 3x3, заповнена нулями:\n{matrix_zeros}\n")

--- Завдання 2: Двовимірний масив 3x3, заповнений нулями ---
Матриця 3x3, заповнена нулями:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [4]:
print("--- Завдання 3: Масив 5x5, випадкові цілі числа від 1 до 10 ---")
matrix_rand_int = np.random.randint(1, 11, size=(5, 5))
print(f"Масив 5x5 з випадковими цілими числами від 1 до 10:\n{matrix_rand_int}\n")


--- Завдання 3: Масив 5x5, випадкові цілі числа від 1 до 10 ---
Масив 5x5 з випадковими цілими числами від 1 до 10:
[[ 9  4  2 10  3]
 [ 3  2  2  6  1]
 [ 6  7  7 10 10]
 [ 7  8  1  6  2]
 [ 4  1  1  8  2]]



In [5]:
print("--- Завдання 4: Масив 4x4, випадкові дійсні числа від 0 до 1 ---")
matrix_rand_float = np.random.rand(4, 4)
print(f"Масив 4x4 з випадковими дійсними числами від 0 до 1:\n{matrix_rand_float}\n")

--- Завдання 4: Масив 4x4, випадкові дійсні числа від 0 до 1 ---
Масив 4x4 з випадковими дійсними числами від 0 до 1:
[[0.39821496 0.95688625 0.64780068 0.19304595]
 [0.45211098 0.54878798 0.38027555 0.33690715]
 [0.09156365 0.24259624 0.43456964 0.05700362]
 [0.75333825 0.15188867 0.21260629 0.03649291]]



In [7]:
print("--- Завдання 5: Два одновимірних масиви 5, випадкові цілі від 1 до 10, поелементні операції ---")
vector_a = np.random.randint(1, 11, size=5)
vector_b = np.random.randint(1, 11, size=5)
print(f"Перший вектор (vector_a):\n{vector_a}")
print(f"Другий вектор (vector_b):\n{vector_b}")
print(f"Додавання (vector_a + vector_b):\n{vector_a + vector_b}")
print(f"Віднімання (vector_a - vector_b):\n{vector_a - vector_b}")
print(f"Множення (vector_a * vector_b):\n{vector_a * vector_b}\n")


--- Завдання 5: Два одновимірних масиви 5, випадкові цілі від 1 до 10, поелементні операції ---
Перший вектор (vector_a):
[ 4 10  9  7  4]
Другий вектор (vector_b):
[1 8 4 7 2]
Додавання (vector_a + vector_b):
[ 5 18 13 14  6]
Віднімання (vector_a - vector_b):
[3 2 5 0 2]
Множення (vector_a * vector_b):
[ 4 80 36 49  8]



In [9]:
print("--- Завдання 6: Два вектори розміром 7, скалярний добуток ---")
vector_c = np.random.rand(7) 
vector_d = np.random.rand(7)
print(f"Перший вектор (vector_c):\n{vector_c}")
print(f"Другий вектор (vector_d):\n{vector_d}")
print(f"Скалярний добуток (np.dot(vector_c, vector_d)): {np.dot(vector_c, vector_d)}\n")

--- Завдання 6: Два вектори розміром 7, скалярний добуток ---
Перший вектор (vector_c):
[0.72678246 0.30542716 0.43073778 0.37830255 0.24843155 0.14397018
 0.76774979]
Другий вектор (vector_d):
[0.76568009 0.66143941 0.97726929 0.36735723 0.97969302 0.40958206
 0.24510132]
Скалярний добуток (np.dot(vector_c, vector_d)): 1.8089541452117912



In [10]:
print("--- Завдання 7: Дві матриці 2x2 та 2x3, перемножити ---")
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
print(f"Перша матриця 2x2:\n{matrix1}")
print(f"Друга матриця 2x3:\n{matrix2}")
# Матричне множення: кількість стовпців першої має дорівнювати кількості рядків другої
# matrix1 (2x2) @ matrix2 (2x3) -> результат (2x3)
product_matrix = np.dot(matrix1, matrix2)
print(f"Добуток матриць:\n{product_matrix}\n")

--- Завдання 7: Дві матриці 2x2 та 2x3, перемножити ---
Перша матриця 2x2:
[[10  5]
 [ 5 10]]
Друга матриця 2x3:
[[8 9 6]
 [9 7 4]]
Добуток матриць:
[[125 125  80]
 [130 115  70]]



In [11]:
print("--- Завдання 8: Матриця 3x3, обернена матриця ---")
# Для оберненої матриці потрібно, щоб вона не була сингулярною.
# Генеруємо матрицю, доки вона не буде оборотною (детермінант не дорівнює 0).
while True:
    matrix_inv = np.random.randint(1, 11, size=(3, 3))
    if np.linalg.det(matrix_inv) != 0:
        break
print(f"Початкова матриця:\n{matrix_inv}")
inverse_matrix = np.linalg.inv(matrix_inv)
print(f"Обернена матриця:\n{inverse_matrix}\n")

--- Завдання 8: Матриця 3x3, обернена матриця ---
Початкова матриця:
[[ 1  6  1]
 [ 7  1  5]
 [10  8  6]]
Обернена матриця:
[[-0.56666667 -0.46666667  0.48333333]
 [ 0.13333333 -0.06666667  0.03333333]
 [ 0.76666667  0.86666667 -0.68333333]]



In [12]:
print("--- Завдання 9: Матриця 4x4, транспонувати ---")
matrix_transpose = np.random.rand(4, 4)
print(f"Початкова матриця:\n{matrix_transpose}")
transposed_matrix = matrix_transpose.T
print(f"Транспонована матриця:\n{transposed_matrix}\n")

--- Завдання 9: Матриця 4x4, транспонувати ---
Початкова матриця:
[[0.98824294 0.70859263 0.21559557 0.8591953 ]
 [0.22894782 0.68431089 0.75904924 0.23510006]
 [0.13660618 0.30003131 0.16544932 0.53711503]
 [0.70423213 0.53606424 0.37308153 0.71314589]]
Транспонована матриця:
[[0.98824294 0.22894782 0.13660618 0.70423213]
 [0.70859263 0.68431089 0.30003131 0.53606424]
 [0.21559557 0.75904924 0.16544932 0.37308153]
 [0.8591953  0.23510006 0.53711503 0.71314589]]



In [13]:
print("--- Завдання 10: Матриця 3x4 та вектор 4, перемножити матрицю на вектор ---")
matrix_mv = np.random.randint(1, 11, size=(3, 4))
vector_mv = np.random.randint(1, 11, size=4)
print(f"Матриця 3x4:\n{matrix_mv}")
print(f"Вектор розміром 4:\n{vector_mv}")
product_mv = np.dot(matrix_mv, vector_mv)
print(f"Добуток матриці на вектор:\n{product_mv}\n")

--- Завдання 10: Матриця 3x4 та вектор 4, перемножити матрицю на вектор ---
Матриця 3x4:
[[ 5  9  5  5]
 [ 2 10  7 10]
 [ 2  4 10  3]]
Вектор розміром 4:
[2 6 6 7]
Добуток матриці на вектор:
[129 176 109]



In [14]:
print("--- Завдання 11: Матриця 2x3 та вектор 3, перемножити матрицю на вектор (дійсні числа) ---")
matrix_mv_float = np.random.rand(2, 3)
vector_mv_float = np.random.rand(3)
print(f"Матриця 2x3:\n{matrix_mv_float}")
print(f"Вектор розміром 3:\n{vector_mv_float}")
# Матриця (2x3) @ Вектор (3,) -> результат (2,)
product_mv_float = np.dot(matrix_mv_float, vector_mv_float)
print(f"Добуток матриці на вектор (дійсні числа):\n{product_mv_float}\n")

--- Завдання 11: Матриця 2x3 та вектор 3, перемножити матрицю на вектор (дійсні числа) ---
Матриця 2x3:
[[0.95476574 0.65047135 0.84315065]
 [0.8513997  0.85204626 0.18621076]]
Вектор розміром 3:
[0.41342566 0.89542378 0.74001882]
Добуток матриці на вектор (дійсні числа):
[1.60111952 1.25273242]



In [15]:
print("--- Завдання 12: Дві матриці 2x2, поелементне множення ---")
matrix_elem1 = np.random.randint(1, 11, size=(2, 2))
matrix_elem2 = np.random.randint(1, 11, size=(2, 2))
print(f"Перша матриця:\n{matrix_elem1}")
print(f"Друга матриця:\n{matrix_elem2}")
elementwise_product = matrix_elem1 * matrix_elem2
print(f"Поелементне множення матриць:\n{elementwise_product}\n")

--- Завдання 12: Дві матриці 2x2, поелементне множення ---
Перша матриця:
[[4 8]
 [5 5]]
Друга матриця:
[[ 8  8]
 [10  9]]
Поелементне множення матриць:
[[32 64]
 [50 45]]



In [16]:
print("--- Завдання 13: Дві матриці 2x2, добуток (матричне множення) ---")
matrix_prod1 = np.random.randint(1, 11, size=(2, 2))
matrix_prod2 = np.random.randint(1, 11, size=(2, 2))
print(f"Перша матриця:\n{matrix_prod1}")
print(f"Друга матриця:\n{matrix_prod2}")
matrix_product = np.dot(matrix_prod1, matrix_prod2) # або matrix_prod1 @ matrix_prod2
print(f"Добуток матриць (матричне множення):\n{matrix_product}\n")

--- Завдання 13: Дві матриці 2x2, добуток (матричне множення) ---
Перша матриця:
[[9 7]
 [7 8]]
Друга матриця:
[[ 9  1]
 [10  5]]
Добуток матриць (матричне множення):
[[151  44]
 [143  47]]



In [17]:
print("--- Завдання 14: Матриця 5x5, сума елементів матриці ---")
matrix_sum_elements = np.random.randint(1, 101, size=(5, 5))
print(f"Матриця 5x5:\n{matrix_sum_elements}")
sum_of_elements = np.sum(matrix_sum_elements)
print(f"Сума всіх елементів матриці: {sum_of_elements}\n")

--- Завдання 14: Матриця 5x5, сума елементів матриці ---
Матриця 5x5:
[[24 63 15 78 60]
 [16 50 59 55 78]
 [47 74 40 32 22]
 [69 17 87 81 20]
 [99 60 32 59 10]]
Сума всіх елементів матриці: 1247



In [18]:
print("--- Завдання 15: Дві матриці 4x4, різниця ---")
matrix_diff1 = np.random.randint(1, 11, size=(4, 4))
matrix_diff2 = np.random.randint(1, 11, size=(4, 4))
print(f"Перша матриця:\n{matrix_diff1}")
print(f"Друга матриця:\n{matrix_diff2}")
difference_matrix = matrix_diff1 - matrix_diff2
print(f"Різниця матриць:\n{difference_matrix}\n")

--- Завдання 15: Дві матриці 4x4, різниця ---
Перша матриця:
[[ 7  2  6  6]
 [ 7  9  7 10]
 [ 3  9  9  5]
 [ 2  7  3  3]]
Друга матриця:
[[ 6  1  9  7]
 [10  4  8  2]
 [10  6  2  6]
 [10  9  1  1]]
Різниця матриць:
[[ 1  1 -3 -1]
 [-3  5 -1  8]
 [-7  3  7 -1]
 [-8 -2  2  2]]



In [19]:
print("--- Завдання 16: Матриця 3x3, вектор-стовпчик з сумою елементів кожного рядка ---")
matrix_row_sum = np.random.rand(3, 3)
print(f"Початкова матриця:\n{matrix_row_sum}")
# np.sum(axis=1) обчислює суму по рядках
row_sums_vector = np.sum(matrix_row_sum, axis=1)
# Перетворюємо результат на вектор-стовпчик (розмірність (3,) на (3,1))
row_sums_column_vector = row_sums_vector.reshape(-1, 1)
print(f"Вектор-стовпчик з сумами елементів кожного рядка:\n{row_sums_column_vector}\n")

--- Завдання 16: Матриця 3x3, вектор-стовпчик з сумою елементів кожного рядка ---
Початкова матриця:
[[0.32978886 0.56413195 0.08702463]
 [0.07375077 0.72426531 0.56378628]
 [0.354312   0.7185675  0.07604226]]
Вектор-стовпчик з сумами елементів кожного рядка:
[[0.98094544]
 [1.36180235]
 [1.14892175]]



In [20]:
print("--- Завдання 17: Матриця 3x4, матриця з квадратами чисел ---")
matrix_original = np.random.randint(1, 11, size=(3, 4))
print(f"Початкова матриця:\n{matrix_original}")
matrix_squares = matrix_original ** 2 # Поелементне піднесення до квадрату
print(f"Матриця з квадратами чисел:\n{matrix_squares}\n")

--- Завдання 17: Матриця 3x4, матриця з квадратами чисел ---
Початкова матриця:
[[5 1 7 3]
 [1 5 8 4]
 [9 3 1 8]]
Матриця з квадратами чисел:
[[25  1 49  9]
 [ 1 25 64 16]
 [81  9  1 64]]



In [21]:
print("--- Завдання 18: Вектор розміром 4, вектор з квадратними коренями ---")
vector_sqrt_original = np.random.randint(1, 51, size=4)
print(f"Початковий вектор:\n{vector_sqrt_original}")
vector_square_roots = np.sqrt(vector_sqrt_original)
print(f"Вектор з квадратними коренями:\n{vector_square_roots}\n")

--- Завдання 18: Вектор розміром 4, вектор з квадратними коренями ---
Початковий вектор:
[48 15 24 35]
Вектор з квадратними коренями:
[6.92820323 3.87298335 4.89897949 5.91607978]

